### ISSUE TITLE
Project does not compile with nom 5

### ISSUE THREAD

**Issue by kryptan** [elmadev/elma-rust#32]
Recent commit has updated nom from 4 to 5 but library does not compile with newer nom version.

**Comment by hexjelly** [comment]
Yea it hasn't worked for a while, and never got around to looking into rewriting the code to work with the new version. It was a mistake to update the dependencies without fixing the error, alas.

**Comment by hexjelly** [comment]
It won't fix the problem you were having with the level since it's very much unrelated, but I'll try to see if I can fix whatever changes is needed with the new nom version.

**Comment by hexjelly** [comment]
Couldn't easily find out how to refactor the nom related code, so for now I just reverted the old commit so master builds again.

Leaving issue open as updating to the new nom 5 API should probably be done at some point anyway. Maybe even look into doing it for the other modules as well where it's not used.

**Comment by hexjelly** [comment]
Fixed by #42
